Hw04 lru cache
ovs325/ovs-otus pull request #4
Opened 2024-05-01 08:30 UTC by ovs325

2024-05-01 08:37 UTC, vladislavmass requested changes

2024-05-01 08:37 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	List []*ListItem
Лист не хранит указатели на все свои элементы. В листе должны быть указатели только на 1 и последний элемент.

2024-05-01 08:37 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +	if lnn > c.capacity {
Размер кэша даже времено не должен превышать капасити.

2024-05-06 03:13 UTC, vladislavmass requested changes

2024-05-06 03:13 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +func (l *list) Len() (num int) {
Данный метода не работает за O(1)

2024-05-06 03:13 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	if l.firstItem == nil {
При добавление 1 элемента он сразу становится и первым и последним. Данный код работает иначе

2024-05-06 03:13 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +func GetLast(item *ListItem) (last *ListItem) {
Get last не работает за O(1)

2024-05-18 21:17 UTC, vladislavmass requested changes

2024-05-18 21:17 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	case l.firstItem:
тут будет паника если мы будем удалять единственный элемент из очереди, так как в 87 строке у нас по сути будет l.firstItem =nil и потом в 88 строке мы попробуем обратится вот так nil.Prev что даст панику

2024-05-18 21:17 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +	if lnn > c.capacity {
Данная проблема не решена. Правильный подход тут сначала проверили на то, что размер равен капасити, после этого если надо делаем удаление и только потом добавляем

2024-05-18 21:17 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +		for key, val := range c.items { // Удаляем ключ из словаря
Данный блок кода не работает за O(1), что противоречит заданию. Рекомендую обратить внимание на следующую строку в тексте задания `Элемент кэша хранит в себе ключ, по которому он лежит в словаре, и само значение.`

2024-05-21 18:21 UTC, vladislavmass requested changes

2024-05-21 18:21 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	if l.firstItem == nil {
Поясните пожалуйста в чем смысл этого ифа, после которого идет корректный код

2024-05-21 18:21 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	case l.lastItem:
И опять мы удаляем единственный элемент из слайса.  Первым case мы зажулили первый элемент, а вот lastiem все еще указывает на удаляемый элемент

2024-05-21 18:32 UTC, ovs325 commented on hw04_lru_cache/list.go
> +	if l.firstItem == nil {
Добрый вечер! Ни чем и не за чем это теперь объяснять. Это осталось от предыдущих реализаций, где первый и последний элемент у меня всегда (даже при одном элементе) отличались.

2024-05-21 18:47 UTC, vladislavmass approved these changes

2024-05-25 12:20 UTC, merged